mycarrotproject/mycarrotapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import set_region_certification

app_name = 'mycarrotapp'

urlpatterns = [
    path("", views.main, name="main"),
    path('trade/', views.trade, name='trade'),
    path('trade_post/<int:pk>/', views.trade_post, name='trade_post'),
    path('write/', views.write, name='write'),
    path('create_form/', views.create_post, name='create_form'),
    path('alert/<str:alert_message>/<str:redirect_url>/', views.alert, name='alert'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('location/', views.location, name='location'),
    path('set_region/', views.set_region, name='set_region'),
    path('set_region_certification/', set_region_certification, name='set_region_certification'),
    path("chat/", views.chat, name="chat"),
    path("chat/<str:room_name>/<str:user_name>/", views.room, name="room"),
    path("room/<int:post_id>/<str:viewer>/", views.get_or_create_room, name="get_or_create_room"),
    path("chatbot/<str:room_name>/<str:user_name>/", views.getGPT, name="getGPT"),
    path('login/', views.user_login, name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='mycarrotapp:main'), name='logout'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
]

mycarrotproject/mycarrotproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mycarrotapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycarrotproject/mycarrotapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to='post_images/') 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, to_field='username')
    created_at = models.DateTimeField(auto_now_add=True, null=True) 

    product_reserved = models.CharField(max_length=1, default='N')  # 예약 여부
    product_sold = models.CharField(max_length=1, default='N')  # 판매 여부

    view_num = models.PositiveIntegerField(default=0)  # 조회 수
    chat_num = models.PositiveIntegerField(default=0)  # 채팅 수

    def save(self, *args, **kwargs):
        update_fields = kwargs.get("update_fields", None)

        if update_fields and "chat_num" not in update_fields:
            chat_num = ChatRoom.objects.filter(post_id=self.id).count()
            self.chat_num = chat_num

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    user_name = models.CharField(max_length=20) # 이름
    nickname = models.CharField(max_length=100,null=True) # 닉네임
    region = models.CharField(max_length=200, null=True) # 지역
    manner_temp = models.FloatField(default=36.5, null=True) # 매너온도
    region_cert = models.CharField(max_length=1, default='N') # 지역인증 여부
    create_date =models.DateTimeField(auto_now_add=True) # 가입일
    # account_id = models.CharField() # 회원 계정 ID
    # password = models.CharField() # 비밀번호

    def __str__(self):
        return f'{self.user.username} Profile'
class ChatRoom(models.Model):
    """Summary
    채팅방 정보 모델

    Attributes:
        room_id (AutoField): _채팅방 식별자_
        post_id (FK): _게시물 id_
        seller (FK): _판매자 id_
        buyer (FK): _구매자 id_
        created_at (DateTimeField): _채팅방 생성 시각_
        updated_at (DateTimeField): _채팅방 최근 수정 시각_
        models (_type_): _description_
    """
    room_id = models.AutoField(primary_key=True)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller_chatrooms")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_chatrooms", null=True)
    latest_chat = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.room_id
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.post_id:
            post = self.post_id
            post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
            post.save(update_fields=["chat_num"])

def post_delete_chatroom(sender, instance, **kwargs):
    if instance.post_id:
        post = instance.post_id
        post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
        post.save(update_fields=["chat_num"])

models.signals.post_delete.connect(post_delete_chatroom, sender=ChatRoom)
    
class Chat(models.Model):
    """_summary_
    채팅 메시지 내역 모델

    Attributes:
        room_id (FK): _ChatRoom의 room_id_
        from_id (FK): _메시지 발신자 id_
        content (TextField): _채팅 내용_
        is_read (BooleanField): _상대방의 메시지 읽음 여부_
        sent_at (DateTimeField): _메시지 전송 시각_
    """
    room_id = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, null=True)
    from_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    is_read = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)

        if self.room_id:
            self.room_id.updated_at = self.sent_at
            self.room_id.latest_chat = self.content
            self.room_id.save(update_fields=["updated_at", "latest_chat"])      

mycarrotproject/mycarrotapp/forms.py
from django import forms
from .models import Post

class CustomLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )

class CustomRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    nickname = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '닉네임을 입력해주세요', 'class': 'login-input'}),
        label='닉네임',
        label_suffix='', 
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 다시 입력해주세요', 'class': 'login-input'}),
        label='비밀번호 확인',
        label_suffix='', 
    )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'price', 'description', 'location', 'images']

mycarrotproject/mycarrotapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomLoginForm, CustomRegistrationForm, PostForm
from .models import Post, UserInfo, ChatRoom, Chat
from django.conf import settings
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
import openai

# Create your views here.

# 메인페이지
def main(request):
    posts = Post.objects.filter(product_sold='N').order_by('-view_num')[:4]
    return render(request, "main.html", {'posts':posts})


# 중고거래 화면
def trade(request):
    top_views_posts = Post.objects.filter(product_sold='N').order_by('-view_num')
    return render(request, 'mycarrotapp/trade.html', {'posts': top_views_posts})

# Alert용 화면
def alert(request, alert_message, redirect_url='location'): # default 값을 'location'으로 설정
    context = {
        'alert_message': alert_message,
        'redirect_url': redirect_url
    }
    return render(request, 'mycarrotapp/alert.html', context)

# 중고거래상세정보(각 포스트) 화면
def trade_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    
    # 조회수 증가
    if request.user.is_authenticated:
        if request.user != post.user:
            post.view_num += 1
            post.save()
        viewer = request.user
    else:
        post.view_num += 1
        post.save()
        viewer = None

    try:
        user_profile = UserInfo.objects.get(user=post.user)
    except UserInfo.DoesNotExist:
            user_profile = None

    context = {
        'post': post,
        'user_profile': user_profile,
        'viewer': viewer,
    }

    return render(request, 'mycarrotapp/trade_post.html', context)

# 거래글쓰기 화면
# @login_required
def write(request):
    try:
        user_profile = UserInfo.objects.get(user_name=request.user)
        
        if user_profile.region_cert == 'Y':
            return render(request, 'mycarrotapp/write.html')
        else:
            return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')
    except UserInfo.DoesNotExist:
        return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')


# 거래글수정 화면
def edit(request, id):
    post = get_object_or_404(Post, id=id)
    if post:
        post.description = post.description.strip()
    if request.method == "POST":
        post.title = request.POST['title']
        post.price = request.POST['price']
        post.description = request.POST['description']
        post.location = request.POST['location']
        if 'images' in request.FILES:
            post.images = request.FILES['images']
        post.save()
        return redirect('mycarrotapp:trade_post', pk=id)

    return render(request, 'mycarrotapp/write.html', {'post': post})

# 포스트 검색
def search(request):
    query = request.GET.get('search')
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(location__icontains=query))
    else:
        results = Post.objects.all()
    
    return render(request, 'mycarrotapp/search.html', {'posts': results})

# 동네인증 화면
@login_required
def location(request):
    try:
        user_profile = UserInfo.objects.get(user_id=request.user)
        region = user_profile.region
    except UserInfo.DoesNotExist:
        region = None

    return render(request, 'mycarrotapp/location.html', {'region': region})

# 포스트 업로드
# @login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # 임시 저장
            post.user = request.user  # 작성자 정보 추가 (이 부분을 수정했습니다)
            post.save()  # 최종 저장
            return redirect('mycarrotapp:trade_post', pk=post.pk)  # 저장 후 상세 페이지로 이동
    else:
        form = PostForm()
    return render(request, 'mycarrotapp/write.html', {'form': form})

def get_chat_rooms(user):
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return context

def chat(request):
    user = request.user.id
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return render(request, "chat/chat.html", context)

# @login_required
def room(request, room_name, user_name):
    if room_name != "999":
        room = ChatRoom.objects.get(pk=room_name)
        user = UserInfo.objects.get(user_name=user_name)
        messages = Chat.objects.filter(room_id=room.pk).order_by("sent_at")
        post = Post.objects.get(pk=room.post_id.id)

        context = {
            "room_name": room,
            "user_name": user,
            "messages": messages,
            "post": post,
        }
    else:
        context = {
            "room_name": room_name,
            "user_name": user_name,
        }
    chat_rooms = get_chat_rooms(request.user.id)
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def get_or_create_room(request, viewer, post_id):
    post = Post.objects.get(pk=post_id)
    viewer = User.objects.get(pk=viewer)
    room, _ = ChatRoom.objects.get_or_create(
        post_id = post,
        buyer=viewer,
        defaults={
            "seller": get_object_or_404(Post, pk=post_id).user
        }
    )

    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room,
        "user_name": viewer,
        "post": post,
    }
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def mark_as_read(request, message_id):
    message = get_object_or_404(Chat, id=message_id)

    message.is_read = True
    message.save()

    return JsonResponse({"status": "success"})

def getGPT(request, room_name, user_name):
    openai.api_key = settings.OPENAI_KEY
    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room_name,
        "user_name": user_name,
    }
    context.update(chat_rooms)
    if request.method == "POST":
        prompt = request.POST.get("prompt")
        response = openai.ChatCompletion(
            model="gpt-3.5-turbo",
            messages=[{
                "role": "user",
                "messages": prompt,
                "max_tokens": 512,
                "temperature": 0.7,
            }]
        )
        return JsonResponse({"response": response})
    
    return render(request, "chat/room.html", context)

# 로그인
def user_login(request):
    if request.user.is_authenticated:
        return redirect('mycarrotapp:main')
    
    else:
        form = CustomLoginForm(data=request.POST or None)
        if request.method == "POST":

            # 입력정보가 유효한 경우 각 필드 정보 가져옴
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                # 위 정보로 사용자 인증(authenticate사용하여 superuser로 로그인 가능)
                user = authenticate(request, username=username, password=password)

                # 로그인이 성공한 경우
                if user is not None:
                    login(request, user) # 로그인 처리 및 세션에 사용자 정보 저장
                    return redirect('mycarrotapp:main')  # 리다이렉션
    return render(request,'login.html',{'form':form})

# 로그아웃
def user_logout(request):
    logout(request)
    return redirect('mycarrotapp:main')


# 회원가입
def register(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        username = request.POST.get('username')
        nickname = request.POST.get('nickname')
        if User.objects.filter(username=username).exists():
            error_message = "이미 존재하는 아이디입니다."
        elif form.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            # 비밀번호 일치 여부를 확인 후 유저 생성 (UserInfo에도 같이 저장)
            if password1 == password2:
                # 새로운 유저를 생성
                user = User.objects.create_user(username=username, password=password1)
                user_info = UserInfo.objects.create(user=user, user_name=username, nickname=nickname)

                return redirect('mycarrotapp:login')
            else:
                # form.add_error('password2', 'Passwords do not match')
                error_message = "비밀번호가 일치하지 않습니다."
    else:
        form = CustomRegistrationForm()

    return render(request, 'register.html', {'form':form, 'error_message': error_message})

# 지역설정
@login_required
def set_region(request):
    if request.method == "POST":
        region = request.POST.get('region-setting')

        if region:
            try:
                user_profile, created = UserInfo.objects.get_or_create(user=request.user)
                user_profile.region = region
                user_profile.save()

                return redirect('mycarrotapp:location')
            except Exception as e:
                return JsonResponse({"status": "error", "message": str(e)})
        else:
            return JsonResponse({"status": "error", "message": "Region cannot be empty"})
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

# 지역인증 완료
@login_required
def set_region_certification(request):
    if request.method == "POST":
        request.user.profile.region_certification = 'Y'
        request.user.profile.save()
        messages.success(request, "인증되었습니다")
        return redirect('mycarrotapp:location')

mycarrotproject/mycarrotapp/templates/footer.html
<div class="footer">
    <div class="container flex-box between">
      <div class="buttons flex-box">
        <a href="#">중고거래</a>
        <a href="#">채팅하기</a>
      </div>
      <div>
        <p class="bold" style="margin-bottom:8px">당근 앱 다운로드</p>
        <div class="download-center">
          <button>App Store</button>
          <button>Google Play</button>
        </div>
      </div>
    </div>
  </div>

mycarrotproject/mycarrotapp/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}"/>
    
    <title>Document</title>
</head>
{% comment %} <body class="back-ye"> {% endcomment %}
<body>
    {% include 'nav_bar.html' %}
  <div class = "back-ye">
    <div class="container">
      {% block content %}
        <div class="login-container">
          <form method="post" class="login-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="login-button">로그인</button>
          </form>
          <p class="register-reco">
            당근마켓 회원이 아니신가요?
            <a href="{% url 'mycarrotapp:register' %}" class="bold">회원가입</a>
          </p>
        </div>
      {% endblock %}
    </div>
  </div>
  </body>

</html>

mycarrotproject/mycarrotapp/templates/main.html
{% load static %}{% load humanize %}
{% comment %} humanize : 시간이나 숫자값을 읽기 좋게 출력하기 위해 사용 (settings.py에 추가) {% endcomment %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <title>Main</title>
</head>

<body>
  {% include 'nav_bar.html' %}

  <div class="content-box section1">
    <div class="container between flex-box">
      <div class="main-box flex-box column">
        <h1>당신 근처의<br>지역 생활 커뮤니티</h1>
        <h4>동네라서 가능한 모든것<br>당근에서 가까운 이웃과 함께해요.</h4>
        <div class="flex-box gap16">
          <button class="flex-box gap8">
            <img src="{% static 'img/icon_googleplay.png' %}" alt="" />Google Play</button>
          <button class="flex-box gap8">
            <img src="{% static 'img/icon_appstore.png' %}" alt="" />App Store</button>
        </div>
      </div>
      <img src="{% static 'img/character.png' %}" alt="" />
    </div>
  </div>
  <div class="content-box section2">
    <div class="container flex-box">
      <img src="{% static 'img/landing1.png' %}" alt="" />
      <div class="description-box">
        <h1>우리 동네<br>중고 직거래 마켓</h1>
        <p>동네 주민들과 가깝고 따뜻한 거래를 지금 경험해보세요</p>

        <a href="{% url 'mycarrotapp:trade' %}">
          <button class="button-gray">인기매물 보기</button>
        </a>
      </div>
    </div>
  </div>
  <div class="content-box section3">
    <div class="container flex-box">
      <div class="section3-text flex-box column gap16 baseline">
        <h1>이웃과 함께 하는<br>동네생활</h1>
        <p>우리 동네의 다양한 이야기를 이웃과 함께 나누어요.</p>
        <div class="flex-box between" style="gap:44px">
          <div class="flex-box column gap8 baseline">
            <img src="{% static 'img/icon_section3_1.png' %}" alt="" />
            <h5>우리 동네질문</h5>
            <h5>궁금한 게 있을 땐 이웃에게 물어보세요</h5>
          </div>
          <div class="flex-box column gap8 baseline">
            <img src="{% static 'img/icon_section3_2.png' %}" alt="" />
            <h5>동네분실센터</h5>
            <h5>무언가를 잃어버렸을 때, 함께 찾을 수 있어요</h5>
          </div>
          <div class="flex-box column gap8 baseline">
            <img src="{% static 'img/icon_section3_3.png' %}" alt="" />
            <h5>동네모임</h5>
            <h5>조회사가 비슷한 이웃과 온오프라인으로 만나요</h5>
          </div>
        </div>
      </div>

      <img src="{% static 'img/landing2.png' %}" alt="" />
    </div>
  </div>
  <div class="content-box section2">
    <div class="container flex-box">
      <img src="{% static 'img/landing3.png' %}" alt="" />
      <div class="description-box">
        <h1>내 근처에서 찾는<br>동네가게</h1>
        <p>우리 동네 가게를 찾고 있나요?<br>동네 주민이 남긴 진짜 후기를 함께 확인해보세요!</p>
      </div>
    </div>
  </div>
  </div>

  <div class="content-box trade-info-section">
    <div class="container trade-section">
      <h1>중고거래 인기매물</h1>
      <div class="full-box trade-box">
        <div class="flex-box full-box card-container between">
          {% for post in posts %}

          <div class="card-box">
            <a href="{% url 'mycarrotapp:trade_post' post.pk %}" class="trade-text-link">
              <div class="card-img">
                {% if post.images %}
                <img src="{{ post.images.url }}" alt="{{ post.title }}">
                {% endif %}
              </div>
              <div class="card-info-box">
                <h5>{{post.title}}</h5>
                <p class="bold">{{ post.price |intcomma}}원</p>
                <p>{{ post.location }}</p>
                <div class="flex-box">
                  <p>조회 {{ post.view_num }}</p>
                  <p>·</p>
                  <p>채팅 {{ post.chat_num }}</p>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}

        </div>
        {% comment %} <a href="/trade">인기매물 더 보기</a> {% endcomment %}
        <a href="{% url 'mycarrotapp:trade' %}">인기매물 더 보기</a>
      </div>
    </div>
  </div>
  {% include 'footer.html' %}

</body>

</html>

mycarrotproject/mycarrotapp/templates/nav_bar.html
{% load static %}
<nav class="navbar">
  <div class="nav-container">
    <a href="{% url 'mycarrotapp:main' %}" class="nav-left">
      <img src="{% static 'img/logo.svg' %}" alt="당근 로고 이미지" />
    </a>
    <div class="nav-menu">
      <a href="/trade" class="trade">중고거래</a>
      {% if user.is_authenticated %}
      <a href="/location" class="home_location">동네인증</a>
      {% endif %}
    </div>
    <div class="nav-right">
      <form method="GET" action="{% url 'mycarrotapp:search' %}">
        <input type="text" name="seach" id="search" class="search" placeholder="물품이나 동네를 검색해보세요" />
      </form>
      {% if user.is_authenticated %}
      <a href="{% url 'mycarrotapp:chat' %}" class="nav-button" id="chat">채팅하기</a>
      <a href="{% url 'mycarrotapp:logout' %}" class="nav-button" id="logout-button">로그아웃</a>
      {% else %}
      <a href="{% url 'mycarrotapp:login' %}" class="nav-button" id="login-button">로그인</a>
      {% endif %}
    </div>
  </div>
  <script src="{% static 'js/nav_bar.js' %}"></script>
</nav>

mycarrotproject/mycarrotapp/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
    <title>회원가입</title>
  </head>

  <body class="back-ye">
    {% include 'nav_bar.html' %}
    <div class="container">
      {% block content %}
        <div class="login-container">
          <form method="post" class="login-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="login-button">등록</button>
          </form>
          <p class="register-reco">
            이미 계정이 있으신가요?
            <a href="{% url 'mycarrotapp:login' %}" class="bold">로그인</a>
          </p>
        </div>
      {% endblock %}
    </div>
    {% if error_message %}
      <script>
        alert('{{ error_message }}');
      </script>
    {% endif %}
  </body>

</html>

mycarrotproject/mycarrotapp/templates/search.html
{% load static %}{% load humanize %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>검색결과</title>
  </head>

  <body>
    {% include 'nav.html' %}
    <div class="post-box">
      <div class="container column center">
        <div class="container column center">
          <div class="full-box trade-box column">
            <div class="flex-box full-box card-container between">
              {% for post in posts %}

                <div class="card-box">
                  <a href="{% url 'mycarrotapp:trade_post' post.pk %}" class="trade-text-link">
                    <div class="card-img">
                      {% comment %} {% if post.images %}
                        <img src="{{ post.images.url }}" alt="{{ post.title }}">
                      {% endif %} {% endcomment %}
                      <img src="" alt="">
                    </div>
                    <div class="card-info-box">
                      <h5>{{ post.title }}</h5>
                      <p class="bold">{{ post.price |intcomma}}원</p>
                      <p>{{ post.location }}</p>
                      <div class="flex-box">
                        <p>조회
                          {{ post.view_num }}</p>
                        <p>·</p>
                        <p>채팅
                          {{ post.chat_num }}</p>
                      </div>
                    </div>
                  </a>
                </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
      {% include 'footer.html' %}
    </body>

  </html>