mycarrotproject/mycarrotapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import set_region_certification

app_name = 'mycarrotapp'

urlpatterns = [
    path("", views.main, name="main"),
    path('trade/', views.trade, name='trade'),
    path('trade_post/<int:pk>/', views.trade_post, name='trade_post'),
    path('write/', views.write, name='write'),
    path('create_form/', views.create_post, name='create_form'),
    path('alert/<str:alert_message>/<str:redirect_url>/', views.alert, name='alert'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('location/', views.location, name='location'),
    path('set_region/', views.set_region, name='set_region'),
    path('set_region_certification/', set_region_certification, name='set_region_certification'),
    path("chat/", views.chat, name="chat"),
    path("chat/<str:room_name>/<str:user_name>/", views.room, name="room"),
    path("room/<int:post_id>/<str:viewer>/", views.get_or_create_room, name="get_or_create_room"),
    path("chatbot/<str:room_name>/<str:user_name>/", views.getGPT, name="getGPT"),
    path('login/', views.user_login, name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='mycarrotapp:main'), name='logout'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
]

mycarrotproject/mycarrotproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mycarrotapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycarrotproject/mycarrotapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to='post_images/') 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, to_field='username')
    created_at = models.DateTimeField(auto_now_add=True, null=True) 

    product_reserved = models.CharField(max_length=1, default='N')  # 예약 여부
    product_sold = models.CharField(max_length=1, default='N')  # 판매 여부

    view_num = models.PositiveIntegerField(default=0)  # 조회 수
    chat_num = models.PositiveIntegerField(default=0)  # 채팅 수

    def save(self, *args, **kwargs):
        update_fields = kwargs.get("update_fields", None)

        if update_fields and "chat_num" not in update_fields:
            chat_num = ChatRoom.objects.filter(post_id=self.id).count()
            self.chat_num = chat_num

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    user_name = models.CharField(max_length=20) # 이름
    nickname = models.CharField(max_length=100,null=True) # 닉네임
    region = models.CharField(max_length=200, null=True) # 지역
    manner_temp = models.FloatField(default=36.5, null=True) # 매너온도
    region_cert = models.CharField(max_length=1, default='N') # 지역인증 여부
    create_date =models.DateTimeField(auto_now_add=True) # 가입일
    # account_id = models.CharField() # 회원 계정 ID
    # password = models.CharField() # 비밀번호

    def __str__(self):
        return f'{self.user.username} Profile'
class ChatRoom(models.Model):
    """Summary
    채팅방 정보 모델

    Attributes:
        room_id (AutoField): _채팅방 식별자_
        post_id (FK): _게시물 id_
        seller (FK): _판매자 id_
        buyer (FK): _구매자 id_
        created_at (DateTimeField): _채팅방 생성 시각_
        updated_at (DateTimeField): _채팅방 최근 수정 시각_
        models (_type_): _description_
    """
    room_id = models.AutoField(primary_key=True)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller_chatrooms")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_chatrooms", null=True)
    latest_chat = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.room_id
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.post_id:
            post = self.post_id
            post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
            post.save(update_fields=["chat_num"])

def post_delete_chatroom(sender, instance, **kwargs):
    if instance.post_id:
        post = instance.post_id
        post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
        post.save(update_fields=["chat_num"])

models.signals.post_delete.connect(post_delete_chatroom, sender=ChatRoom)
    
class Chat(models.Model):
    """_summary_
    채팅 메시지 내역 모델

    Attributes:
        room_id (FK): _ChatRoom의 room_id_
        from_id (FK): _메시지 발신자 id_
        content (TextField): _채팅 내용_
        is_read (BooleanField): _상대방의 메시지 읽음 여부_
        sent_at (DateTimeField): _메시지 전송 시각_
    """
    room_id = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, null=True)
    from_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    is_read = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)

        if self.room_id:
            self.room_id.updated_at = self.sent_at
            self.room_id.latest_chat = self.content
            self.room_id.save(update_fields=["updated_at", "latest_chat"])      

mycarrotproject/mycarrotapp/forms.py
from django import forms
from .models import Post

class CustomLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )

class CustomRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    nickname = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '닉네임을 입력해주세요', 'class': 'login-input'}),
        label='닉네임',
        label_suffix='', 
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 다시 입력해주세요', 'class': 'login-input'}),
        label='비밀번호 확인',
        label_suffix='', 
    )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'price', 'description', 'location', 'images']

mycarrotproject/mycarrotapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomLoginForm, CustomRegistrationForm, PostForm
from .models import Post, UserInfo, ChatRoom, Chat
from django.conf import settings
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
import openai

# Create your views here.

# 메인페이지
def main(request):
    posts = Post.objects.filter(product_sold='N').order_by('-view_num')[:4]
    return render(request, "main.html", {'posts':posts})


# 중고거래 화면
def trade(request):
    top_views_posts = Post.objects.filter(product_sold='N').order_by('-view_num')
    return render(request, 'mycarrotapp/trade.html', {'posts': top_views_posts})

# Alert용 화면
def alert(request, alert_message, redirect_url='location'): # default 값을 'location'으로 설정
    context = {
        'alert_message': alert_message,
        'redirect_url': redirect_url
    }
    return render(request, 'mycarrotapp/alert.html', context)

# 중고거래상세정보(각 포스트) 화면
def trade_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    
    # 조회수 증가
    if request.user.is_authenticated:
        if request.user != post.user:
            post.view_num += 1
            post.save()
        viewer = request.user
    else:
        post.view_num += 1
        post.save()
        viewer = None

    try:
        user_profile = UserInfo.objects.get(user=post.user)
    except UserInfo.DoesNotExist:
            user_profile = None

    context = {
        'post': post,
        'user_profile': user_profile,
        'viewer': viewer,
    }

    return render(request, 'mycarrotapp/trade_post.html', context)

# 거래글쓰기 화면
# @login_required
def write(request):
    try:
        user_profile = UserInfo.objects.get(user_name=request.user)
        
        if user_profile.region_cert == 'Y':
            return render(request, 'mycarrotapp/write.html')
        else:
            return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')
    except UserInfo.DoesNotExist:
        return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')


# 거래글수정 화면
def edit(request, id):
    post = get_object_or_404(Post, id=id)
    if post:
        post.description = post.description.strip()
    if request.method == "POST":
        post.title = request.POST['title']
        post.price = request.POST['price']
        post.description = request.POST['description']
        post.location = request.POST['location']
        if 'images' in request.FILES:
            post.images = request.FILES['images']
        post.save()
        return redirect('mycarrotapp:trade_post', pk=id)

    return render(request, 'mycarrotapp/write.html', {'post': post})

# 포스트 검색
def search(request):
    query = request.GET.get('search')
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(location__icontains=query))
    else:
        results = Post.objects.all()
    
    return render(request, 'mycarrotapp/search.html', {'posts': results})

# 동네인증 화면
@login_required
def location(request):
    try:
        user_profile = UserInfo.objects.get(user_id=request.user)
        region = user_profile.region
    except UserInfo.DoesNotExist:
        region = None

    return render(request, 'mycarrotapp/location.html', {'region': region})

# 포스트 업로드
# @login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # 임시 저장
            post.user = request.user  # 작성자 정보 추가 (이 부분을 수정했습니다)
            post.save()  # 최종 저장
            return redirect('mycarrotapp:trade_post', pk=post.pk)  # 저장 후 상세 페이지로 이동
    else:
        form = PostForm()
    return render(request, 'mycarrotapp/write.html', {'form': form})

def get_chat_rooms(user):
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return context

def chat(request):
    user = request.user.id
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return render(request, "chat/chat.html", context)

# @login_required
def room(request, room_name, user_name):
    if room_name != "999":
        room = ChatRoom.objects.get(pk=room_name)
        user = UserInfo.objects.get(user_name=user_name)
        messages = Chat.objects.filter(room_id=room.pk).order_by("sent_at")
        post = Post.objects.get(pk=room.post_id.id)

        context = {
            "room_name": room,
            "user_name": user,
            "messages": messages,
            "post": post,
        }
    else:
        context = {
            "room_name": room_name,
            "user_name": user_name,
        }
    chat_rooms = get_chat_rooms(request.user.id)
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def get_or_create_room(request, viewer, post_id):
    post = Post.objects.get(pk=post_id)
    viewer = User.objects.get(pk=viewer)
    room, _ = ChatRoom.objects.get_or_create(
        post_id = post,
        buyer=viewer,
        defaults={
            "seller": get_object_or_404(Post, pk=post_id).user
        }
    )

    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room,
        "user_name": viewer,
        "post": post,
    }
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def mark_as_read(request, message_id):
    message = get_object_or_404(Chat, id=message_id)

    message.is_read = True
    message.save()

    return JsonResponse({"status": "success"})

def getGPT(request, room_name, user_name):
    openai.api_key = settings.OPENAI_KEY
    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room_name,
        "user_name": user_name,
    }
    context.update(chat_rooms)
    if request.method == "POST":
        prompt = request.POST.get("prompt")
        response = openai.ChatCompletion(
            model="gpt-3.5-turbo",
            messages=[{
                "role": "user",
                "messages": prompt,
                "max_tokens": 512,
                "temperature": 0.7,
            }]
        )
        return JsonResponse({"response": response})
    
    return render(request, "chat/room.html", context)

# 로그인
def user_login(request):
    if request.user.is_authenticated:
        return redirect('mycarrotapp:main')
    
    else:
        form = CustomLoginForm(data=request.POST or None)
        if request.method == "POST":

            # 입력정보가 유효한 경우 각 필드 정보 가져옴
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                # 위 정보로 사용자 인증(authenticate사용하여 superuser로 로그인 가능)
                user = authenticate(request, username=username, password=password)

                # 로그인이 성공한 경우
                if user is not None:
                    login(request, user) # 로그인 처리 및 세션에 사용자 정보 저장
                    return redirect('mycarrotapp:main')  # 리다이렉션
    return render(request,'login.html',{'form':form})

# 로그아웃
def user_logout(request):
    logout(request)
    return redirect('mycarrotapp:main')


# 회원가입
def register(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        username = request.POST.get('username')
        nickname = request.POST.get('nickname')
        if User.objects.filter(username=username).exists():
            error_message = "이미 존재하는 아이디입니다."
        elif form.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            # 비밀번호 일치 여부를 확인 후 유저 생성 (UserInfo에도 같이 저장)
            if password1 == password2:
                # 새로운 유저를 생성
                user = User.objects.create_user(username=username, password=password1)
                user_info = UserInfo.objects.create(user=user, user_name=username, nickname=nickname)

                return redirect('mycarrotapp:login')
            else:
                # form.add_error('password2', 'Passwords do not match')
                error_message = "비밀번호가 일치하지 않습니다."
    else:
        form = CustomRegistrationForm()

    return render(request, 'register.html', {'form':form, 'error_message': error_message})

# 지역설정
@login_required
def set_region(request):
    if request.method == "POST":
        region = request.POST.get('region-setting')

        if region:
            try:
                user_profile, created = UserInfo.objects.get_or_create(user=request.user)
                user_profile.region = region
                user_profile.save()

                return redirect('mycarrotapp:location')
            except Exception as e:
                return JsonResponse({"status": "error", "message": str(e)})
        else:
            return JsonResponse({"status": "error", "message": "Region cannot be empty"})
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

# 지역인증 완료
@login_required
def set_region_certification(request):
    if request.method == "POST":
        request.user.profile.region_certification = 'Y'
        request.user.profile.save()
        messages.success(request, "인증되었습니다")
        return redirect('mycarrotapp:location')

mycarrotproject/mycarrotapp/templates/chat/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>Chat</title>
  </head>

  <body>
    {% include 'nav_bar.html' %}
    <div class="container">
      <div class="chat-container">
        <nav class="chat-list-container">
          <div class="my-id">
            <div class="nickname-area">내 아이디</div>
            <label class="unread-messages">
              <span class="unread-description">안 읽은 메시지만 보기</span>
              <input type="checkbox" name="" class="checkbox" />
            </label>
          </div>
          <a class="chatbot-box" href="{% url 'mycarrotapp:room' room_name='999' user_name=request.user.username %}">
            <img src="{% static 'img/icon_aibot.png' %}" alt="" />
            <div style="margin-left: 9px">
              <div class="chatbot-title">AI 챗봇</div>
              <div class="chatbot-desc">궁금한 내용을 물어보세요!</div>
            </div>
          </a>
          <ul class="chat-list-box">
            <li class="chat-room">
              <a class="chat-room-link" href="{% url 'mycarrotapp:room' room_name='lobby' user_name='user2' %}">
                <div class="chat-preview-box">
                  <div class="preview-title">
                    <span class="preview-nickname">상대방아이디</span>
                    <div class="preview-text">
                      <span>여의도동</span>
                      <span> · </span>
                      <span>1년 전</span>
                    </div>
                  </div>
                  <div class="preview-description">
                    <span class="description-text">거래 잘 하셨나요? ㅋ</span>
                  </div>
                </div>
                <img class="preview-image" src="{% static 'img/product-preview.webp' %}" alt="거래 품목 썸네일" />
              </a>
            </li>
            <li class="chat-room">
              <a class="chat-room-link" href="">
                <div class="chat-preview-box">
                  <div class="preview-title">
                    <span class="preview-nickname">상대방아이디</span>
                    <div class="preview-text">
                      <span>여의도동</span>
                      <span> · </span>
                      <span>1년 전</span>
                    </div>
                  </div>
                  <div class="preview-description">
                    <span class="description-text">거래 잘 하셨나요? ㅋ</span>
                  </div>
                </div>
                <img class="preview-image" src="{% static 'img/product-preview.webp' %}" alt="거래 품목 썸네일" />
              </a>
            </li>
            {% for room in rooms %}
            {% with post=room.post_id %}
            <li class="chat-room">
              <a class="chat-room-link" href="{% url 'mycarrotapp:room' room_name=room.pk user_name=request.user.username %}" >
                <div class="chat-preview-box">
                  <div class="preview-title">
                    <span class="preview-nickname">
                      {% if request.user.id != room.seller.id %}
                        {{ room.seller }}
                      {% else %}
                        {{ room.buyer }}
                      {% endif %}
                    </span>
                    <div class="preview-text">
                      <span>{{ post.location }}</span>
                      <span> · </span>
                      <span>{{ post.created_at|timesince }}</span>
                    </div>
                  </div>
                  <div class="preview-description">
                    <span class="description-text">{{ room.latest_chat }}</span>
                  </div>
                </div>
                <img class="preview-image" src="{{ post.images.url }}" alt="거래 품목 썸네일" />
              </a>
            </li>
            {% endwith %}
            {% endfor %}
          </ul>
        </nav>
        <main class="chat-main-container">
          {% block content%}
          <div class="empty-box">
            <img src="{% static 'img/chat.svg' %}" alt="" />
            <div class="empty-description">채팅할 상대를 선택하세요.</div>
          </div>
          {% endblock %}
        </main>
      </div>
    </div>
  </body>
</html>