mycarrotproject/mycarrotapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import set_region_certification

app_name = 'mycarrotapp'

urlpatterns = [
    path("", views.main, name="main"),
    path('trade/', views.trade, name='trade'),
    path('trade_post/<int:pk>/', views.trade_post, name='trade_post'),
    path('write/', views.write, name='write'),
    path('create_form/', views.create_post, name='create_form'),
    path('alert/<str:alert_message>/<str:redirect_url>/', views.alert, name='alert'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('location/', views.location, name='location'),
    path('set_region/', views.set_region, name='set_region'),
    path('set_region_certification/', set_region_certification, name='set_region_certification'),
    path("chat/", views.chat, name="chat"),
    path("chat/<str:room_name>/<str:user_name>/", views.room, name="room"),
    path("room/<int:post_id>/<str:viewer>/", views.get_or_create_room, name="get_or_create_room"),
    path("chatbot/<str:room_name>/<str:user_name>/", views.getGPT, name="getGPT"),
    path('login/', views.user_login, name='login'),
    # path('logout/', auth_views.LogoutView.as_view(next_page='mycarrotapp:main'), name='logout'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
]

mycarrotproject/mycarrotproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mycarrotapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mycarrotproject/mycarrotapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    description = models.TextField()
    location = models.CharField(max_length=100)
    images = models.ImageField(upload_to='post_images/') 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, to_field='username')
    created_at = models.DateTimeField(auto_now_add=True, null=True) 

    product_reserved = models.CharField(max_length=1, default='N')  # 예약 여부
    product_sold = models.CharField(max_length=1, default='N')  # 판매 여부

    view_num = models.PositiveIntegerField(default=0)  # 조회 수
    chat_num = models.PositiveIntegerField(default=0)  # 채팅 수

    def save(self, *args, **kwargs):
        update_fields = kwargs.get("update_fields", None)

        if update_fields and "chat_num" not in update_fields:
            chat_num = ChatRoom.objects.filter(post_id=self.id).count()
            self.chat_num = chat_num

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_at']

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    user_name = models.CharField(max_length=20) # 이름
    nickname = models.CharField(max_length=100,null=True) # 닉네임
    region = models.CharField(max_length=200, null=True) # 지역
    manner_temp = models.FloatField(default=36.5, null=True) # 매너온도
    region_cert = models.CharField(max_length=1, default='N') # 지역인증 여부
    create_date =models.DateTimeField(auto_now_add=True) # 가입일
    # account_id = models.CharField() # 회원 계정 ID
    # password = models.CharField() # 비밀번호

    def __str__(self):
        return f'{self.user.username} Profile'
class ChatRoom(models.Model):
    """Summary
    채팅방 정보 모델

    Attributes:
        room_id (AutoField): _채팅방 식별자_
        post_id (FK): _게시물 id_
        seller (FK): _판매자 id_
        buyer (FK): _구매자 id_
        created_at (DateTimeField): _채팅방 생성 시각_
        updated_at (DateTimeField): _채팅방 최근 수정 시각_
        models (_type_): _description_
    """
    room_id = models.AutoField(primary_key=True)
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller_chatrooms")
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="buyer_chatrooms", null=True)
    latest_chat = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.room_id
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.post_id:
            post = self.post_id
            post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
            post.save(update_fields=["chat_num"])

def post_delete_chatroom(sender, instance, **kwargs):
    if instance.post_id:
        post = instance.post_id
        post.chat_num = ChatRoom.objects.filter(post_id=post.id).count()
        post.save(update_fields=["chat_num"])

models.signals.post_delete.connect(post_delete_chatroom, sender=ChatRoom)
    
class Chat(models.Model):
    """_summary_
    채팅 메시지 내역 모델

    Attributes:
        room_id (FK): _ChatRoom의 room_id_
        from_id (FK): _메시지 발신자 id_
        content (TextField): _채팅 내용_
        is_read (BooleanField): _상대방의 메시지 읽음 여부_
        sent_at (DateTimeField): _메시지 전송 시각_
    """
    room_id = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, null=True)
    from_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField()
    is_read = models.BooleanField(default=False)
    sent_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs) -> None:
        super().save(*args, **kwargs)

        if self.room_id:
            self.room_id.updated_at = self.sent_at
            self.room_id.latest_chat = self.content
            self.room_id.save(update_fields=["updated_at", "latest_chat"])      

mycarrotproject/mycarrotapp/forms.py
from django import forms
from .models import Post

class CustomLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )

class CustomRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '아이디를 입력해주세요', 'class': 'login-input'}),
        label='아이디',
        label_suffix='', 
    )
    nickname = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '닉네임을 입력해주세요', 'class': 'login-input'}),
        label='닉네임',
        label_suffix='', 
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 입력해주세요', 'class': 'login-input'}),
        label='비밀번호',
        label_suffix='', 
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호를 다시 입력해주세요', 'class': 'login-input'}),
        label='비밀번호 확인',
        label_suffix='', 
    )

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'price', 'description', 'location', 'images']

mycarrotproject/mycarrotapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomLoginForm, CustomRegistrationForm, PostForm
from .models import Post, UserInfo, ChatRoom, Chat
from django.conf import settings
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
import openai

# Create your views here.

# 메인페이지
def main(request):
    posts = Post.objects.filter(product_sold='N').order_by('-view_num')[:4]
    return render(request, "main.html", {'posts':posts})


# 중고거래 화면
def trade(request):
    top_views_posts = Post.objects.filter(product_sold='N').order_by('-view_num')
    return render(request, 'mycarrotapp/trade.html', {'posts': top_views_posts})

# Alert용 화면
def alert(request, alert_message, redirect_url='location'): # default 값을 'location'으로 설정
    context = {
        'alert_message': alert_message,
        'redirect_url': redirect_url
    }
    return render(request, 'mycarrotapp/alert.html', context)

# 중고거래상세정보(각 포스트) 화면
def trade_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    
    # 조회수 증가
    if request.user.is_authenticated:
        if request.user != post.user:
            post.view_num += 1
            post.save()
        viewer = request.user
    else:
        post.view_num += 1
        post.save()
        viewer = None

    try:
        user_profile = UserInfo.objects.get(user=post.user)
    except UserInfo.DoesNotExist:
            user_profile = None

    context = {
        'post': post,
        'user_profile': user_profile,
        'viewer': viewer,
    }

    return render(request, 'mycarrotapp/trade_post.html', context)

# 거래글쓰기 화면
# @login_required
def write(request):
    try:
        user_profile = UserInfo.objects.get(user_name=request.user)
        
        if user_profile.region_cert == 'Y':
            return render(request, 'mycarrotapp/write.html')
        else:
            return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')
    except UserInfo.DoesNotExist:
        return redirect('mycarrotapp:alert', alert_message='동네인증이 필요합니다.', redirect_url='location')


# 거래글수정 화면
def edit(request, id):
    post = get_object_or_404(Post, id=id)
    if post:
        post.description = post.description.strip()
    if request.method == "POST":
        post.title = request.POST['title']
        post.price = request.POST['price']
        post.description = request.POST['description']
        post.location = request.POST['location']
        if 'images' in request.FILES:
            post.images = request.FILES['images']
        post.save()
        return redirect('mycarrotapp:trade_post', pk=id)

    return render(request, 'mycarrotapp/write.html', {'post': post})

# 포스트 검색
def search(request):
    query = request.GET.get('search')
    if query:
        results = Post.objects.filter(Q(title__icontains=query) | Q(location__icontains=query))
    else:
        results = Post.objects.all()
    
    return render(request, 'mycarrotapp/search.html', {'posts': results})

# 동네인증 화면
@login_required
def location(request):
    try:
        user_profile = UserInfo.objects.get(user_id=request.user)
        region = user_profile.region
    except UserInfo.DoesNotExist:
        region = None

    return render(request, 'mycarrotapp/location.html', {'region': region})

# 포스트 업로드
# @login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)  # 임시 저장
            post.user = request.user  # 작성자 정보 추가 (이 부분을 수정했습니다)
            post.save()  # 최종 저장
            return redirect('mycarrotapp:trade_post', pk=post.pk)  # 저장 후 상세 페이지로 이동
    else:
        form = PostForm()
    return render(request, 'mycarrotapp/write.html', {'form': form})

def get_chat_rooms(user):
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return context

def chat(request):
    user = request.user.id
    rooms = ChatRoom.objects.filter(Q(buyer=user) | Q(seller=user)).order_by("-updated_at")
    posts = [get_object_or_404(Post, pk=room.post_id.pk) for room in rooms]
    context = { "rooms": rooms, "posts": posts }
    return render(request, "chat/chat.html", context)

# @login_required
def room(request, room_name, user_name):
    if room_name != "999":
        room = ChatRoom.objects.get(pk=room_name)
        user = UserInfo.objects.get(user_name=user_name)
        messages = Chat.objects.filter(room_id=room.pk).order_by("sent_at")
        post = Post.objects.get(pk=room.post_id.id)

        context = {
            "room_name": room,
            "user_name": user,
            "messages": messages,
            "post": post,
        }
    else:
        context = {
            "room_name": room_name,
            "user_name": user_name,
        }
    chat_rooms = get_chat_rooms(request.user.id)
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def get_or_create_room(request, viewer, post_id):
    post = Post.objects.get(pk=post_id)
    viewer = User.objects.get(pk=viewer)
    room, _ = ChatRoom.objects.get_or_create(
        post_id = post,
        buyer=viewer,
        defaults={
            "seller": get_object_or_404(Post, pk=post_id).user
        }
    )

    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room,
        "user_name": viewer,
        "post": post,
    }
    context.update(chat_rooms)
    return render(request, "chat/room.html", context)

def mark_as_read(request, message_id):
    message = get_object_or_404(Chat, id=message_id)

    message.is_read = True
    message.save()

    return JsonResponse({"status": "success"})

def getGPT(request, room_name, user_name):
    openai.api_key = settings.OPENAI_KEY
    chat_rooms = get_chat_rooms(request.user.id)
    context = {
        "room_name": room_name,
        "user_name": user_name,
    }
    context.update(chat_rooms)
    if request.method == "POST":
        prompt = request.POST.get("prompt")
        response = openai.ChatCompletion(
            model="gpt-3.5-turbo",
            messages=[{
                "role": "user",
                "messages": prompt,
                "max_tokens": 512,
                "temperature": 0.7,
            }]
        )
        return JsonResponse({"response": response})
    
    return render(request, "chat/room.html", context)

# 로그인
def user_login(request):
    if request.user.is_authenticated:
        return redirect('mycarrotapp:main')
    
    else:
        form = CustomLoginForm(data=request.POST or None)
        if request.method == "POST":

            # 입력정보가 유효한 경우 각 필드 정보 가져옴
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']

                # 위 정보로 사용자 인증(authenticate사용하여 superuser로 로그인 가능)
                user = authenticate(request, username=username, password=password)

                # 로그인이 성공한 경우
                if user is not None:
                    login(request, user) # 로그인 처리 및 세션에 사용자 정보 저장
                    return redirect('mycarrotapp:main')  # 리다이렉션
    return render(request,'login.html',{'form':form})

# 로그아웃
def user_logout(request):
    logout(request)
    return redirect('mycarrotapp:main')


# 회원가입
def register(request):
    error_message = ''
    if request.method == 'POST':
        form = CustomRegistrationForm(request.POST)
        username = request.POST.get('username')
        nickname = request.POST.get('nickname')
        if User.objects.filter(username=username).exists():
            error_message = "이미 존재하는 아이디입니다."
        elif form.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            # 비밀번호 일치 여부를 확인 후 유저 생성 (UserInfo에도 같이 저장)
            if password1 == password2:
                # 새로운 유저를 생성
                user = User.objects.create_user(username=username, password=password1)
                user_info = UserInfo.objects.create(user=user, user_name=username, nickname=nickname)

                return redirect('mycarrotapp:login')
            else:
                # form.add_error('password2', 'Passwords do not match')
                error_message = "비밀번호가 일치하지 않습니다."
    else:
        form = CustomRegistrationForm()

    return render(request, 'register.html', {'form':form, 'error_message': error_message})

# 지역설정
@login_required
def set_region(request):
    if request.method == "POST":
        region = request.POST.get('region-setting')

        if region:
            try:
                user_profile, created = UserInfo.objects.get_or_create(user=request.user)
                user_profile.region = region
                user_profile.save()

                return redirect('mycarrotapp:location')
            except Exception as e:
                return JsonResponse({"status": "error", "message": str(e)})
        else:
            return JsonResponse({"status": "error", "message": "Region cannot be empty"})
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

# 지역인증 완료
@login_required
def set_region_certification(request):
    if request.method == "POST":
        request.user.profile.region_certification = 'Y'
        request.user.profile.save()
        messages.success(request, "인증되었습니다")
        return redirect('mycarrotapp:location')

mycarrotproject/mycarrotapp/templates/mycarrotapp/alert.html
<!DOCTYPE html>
<html>

  <head>
    <title>당근</title>
  </head>

  <body>
    <script type="text/javascript">
      alert('{{ alert_message }}');
      {% if redirect_url == "location" %}
        window.location.href = '{% url "mycarrotapp:location" %}';
      {% elif redirect_url == "current" %}
        window.history.back();
      {% else %}
        window.history.back();
      {% endif %}
    </script>
  </body>

</html>

mycarrotproject/mycarrotapp/templates/mycarrotapp/location.html
{% load static %}

<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/location.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
    <title>동네인증</title>
</head>

<body class="back-ye">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
    </div>
    {% endfor %}
    </div>
    {% endif %}
    {% include 'nav_bar.html' %}
    <div class="content-box">
        <div class="container column center">
            <div class="region-setting-box full-box">
                <label for="region-setting">내 동네 설정</label>
                <form method="POST" action="/set_region/" id="region-form">
                    {% csrf_token %}
                    <div class="flex-box full-box between region-input">
                        <input type="text" id="region-setting" class="region-setting" name="region-setting"
                            placeholder="예) 서울 강서구 화곡동" value="{% if region %}{{ region }}{% endif %}">
                        <button type="submit" class="ghost-button orange region-setting" style="width:15%"
                            id="set-region-button">
                            {% if region %}
                            수정
                            {% else %}
                            저장
                            {% endif %}
                        </button>

                    </div>
                </form>
            </div>
            <div id="map" style="width: 100%; height: 468px; margin-top: 44px"></div>
            <h5 id="region-info">현재 위치는</h5>
            <h5 id="region-judge"></h5>
            <form id="region-certification-form" method="POST" action="/set_region_certification/" class="full-box">
                {% csrf_token %}
                <button id="region-save-button" class="primary-button">동네인증하기</button>
            </form>
        </div>
    </div>
    {% include 'footer.html' %}

    <!--카카오 api key-->
    <script type="text/javascript"
        src="//dapi.kakao.com/v2/maps/sdk.js?appkey=06b71a5db40aca812f7ae8bff82d58b9&libraries=services"></script>

    <script type="text/javascript" src="{% static 'js/location.js' %}"></script>
</body>

</html>

mycarrotproject/mycarrotapp/templates/mycarrotapp/trade.html
{% load custom_filter%}
{% load static %}{% load humanize %}
<!DOCTYPE html>
<html>

<head>
    <title>중고거래</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/trade.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
</head>

<body>
    {% include 'nav_bar.html' %}
    <div class="content-box">
        <a href="{% url 'mycarrotapp:write' %}">
            <div class="floating-button">
                거래글쓰기
            </div>
        </a>
        <div class="about-trade">
            <div class="container ">
                <div class="trade-text">
                    <h3>믿을만한</br>이웃 간 중고거래</h3>
                    <p>동네 주민들과 가깝고 따뜻한 거래를</br>지금 경험해보세요.</p>
                </div>
                <div class="thumbnail-img">
                    <img src="{% static 'img/img1.png' %}" alt="" />
                </div>
            </div>
        </div>

        <div class="post-box">
            <div class="container column center">
                <h1>중고거래 인기매물</h1>
            </div>
            <div class="container column center">
                <div class="full-box trade-box column">
                    <div class="flex-box full-box card-container between">
                        {% for post in posts %}

                        <div class="card-box">
                            <a href="{% url 'mycarrotapp:trade_post' post.pk %}" class="trade-text-link">
                                <div class="card-img">
                                    {% if post.images %}
                                    <img src="{{ post.images.url }}" alt="{{ post.title }}">
                                    {% endif %}
                                </div>
                                <div class="card-info-box">
                                    <h5>{{ post.title }}</h5>
                                    <p class="bold">{{ post.price |intcomma}}원</p>
                                    <p>{{ post.location }}</p>
                                    <div class="flex-box">
                                        <p>조회
                                            {{ post.view_num }}</p>
                                        <p>·</p>
                                        <p>채팅
                                            {{ post.chat_num }}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
        {% include 'footer.html' %}

</body>

</html>

mycarrotproject/mycarrotapp/templates/mycarrotapp/trade_post.html
{% load static%}{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/trade_post.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
    <title>중고거래 상세보기</title>
</head>

<body>
    {% include 'nav_bar.html' %}
    <div class="content-box">
        <div class="container column">
            <div class="post-box">
                {% block content %}
                <img src="{{ post.images.url }}" alt="{{ post.title }}" class="block-box">
                <div class="flex-box between info-button-box">
                    <div class="user-info">
                        <h6>{{ post.user }}</h6>
                        <p>{{ user_profile.region }}</p>
                    </div>
                    {% if request.user.username == post.user.username %}
                    <div class="flex-box button-box">
                        <a href="{% url 'mycarrotapp:edit' post.id %}">
                            <button class="grey">수정하기</button>
                        </a>
                        <a href="{% url 'mycarrotapp:chat' %}">
                            <button class="orange">채팅보기</button>
                        </a>
                    </div>
                    {% else %}
                    <div class="button-box">
                        <a href="{% url 'mycarrotapp:get_or_create_room' post_id=post.id viewer=request.user.id %}">
                            <button class="orange">채팅하기</button>
                        </a>
                    </div>
                    {% endif %}
                </div>
                <hr class="line">
                <div class="post-info-box">
                    <div class="flex-box between">
                        <h3>{{ post.title }}</h3>
                        <h3>{{ post.price |intcomma}}
                            원</h3>
                    </div>
                    <p>{{ post.description }}</p>
                    <div class="location-views-box flex-box between">
                        <p>희망 거래장소 |
                            {{ post.location }}</p>
                        <p>조회수
                            {{ post.view_num }}</p>
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'footer.html' %}

</body>

</html>

mycarrotproject/mycarrotapp/templates/mycarrotapp/write.html
{% load custom_filter%}
{% load static%}{% load humanize %}
<!DOCTYPE html>
<html>

<head>
    <title>거래 글쓰기</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/write.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/nav_bar.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}" />
</head>

<body>
    {% include 'nav_bar.html' %}
    <div class="content-box">
        <div class="container">

            {% block content %}
            <div class="about-trade">
                <div class="container">
                    <form class="write-box" method="POST"
                        action="{% if post %}{% url 'mycarrotapp:edit' post.id %}{% else %}{% url 'mycarrotapp:create_form' %}{% endif %}"
                        enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="flex-box">
                            <label class="img-upload">
                                <img src="{% if post %}{{ post.images.url }}{% else %}{% static 'img/icon_photo.png' %}{% endif %}"
                                    alt="이미지 설명" id="imagePreview">
                                <input type="file" name="images" accept="image/*" style="display: none;"
                                    onchange="previewImage(event);">
                            </label>
                            <div>
                                <div class="flex-box column baseline title-box">
                                    <label for="title">글 제목</label>
                                    <input type="text" name="title" placeholder="글 제목" required="required"
                                        value="{% if post %}{{ post.title }}{% endif %}">
                                    <label for=" price">가격</label>
                                    <input type="text" name="price" placeholder="가격" required="required"
                                        value="{% if post %}{{ post.price }}{% endif %}">
                                </div>
                            </div>
                        </div>
                        <div class="full-box">
                            <label for="description" class="block-box">물품 설명</label>
                            <textarea name="description" required="required">
                    {% if post %}{{ post.description }}
                    {% endif %}
                  </textarea>

                        </div>
                        <div class="full-box">
                            <label for="location" class="block-box">거래 희망 장소</label>
                            <input type="text" name="location" placeholder="거래를 희망하는 장소" required="required"
                                value="{% if post %}{{ post.location }}{% endif %}">
                        </div>
                        <div class="submit-button-box">
                            {% if post %}
                            <button type="submit">수정하기</button>
                            {% else %}
                            <button type="submit">전송</button>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
            {% endblock %}

            <script type="text/javascript" src="{% static 'js/write.js' %}"></script>

</body>

</html>